export { default as PHome } from './PHome'
export { default as PAbout } from './PAbout'
export { default as PLogin } from './PLogin'
export { default as PGameCreate } from './PGameCreate'
export { default as PGame } from './PGame'
